# SPDX-FileCopyrightText: 2025 Istituto Nazionale di Fisica Nucleare
#
# SPDX-License-Identifier: EUPL-1.2

stages:
  - build-ci
  - build
  - test
  - deploy

variables:
  VCPKG_DEFAULT_BINARY_CACHE: $CI_PROJECT_DIR/.cache/vcpkg

build-ci:
  stage: build-ci
  image: docker:latest
  tags: [fast]
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker buildx inspect multiarch || docker buildx create --name multiarch --driver docker-container --use
  script:
    # - docker buildx build --platform linux/amd64,linux/arm64 --pull --push -t $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG .devcontainer
    - docker buildx build --platform linux/amd64 --pull --push -t $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG .devcontainer
  rules:
    - changes:
      - .devcontainer/**/*
      - vcpkg.json
      - vcpkg-configuration.json
      - .gitlab-ci.yml

build-storm-tape:
  stage: build
  image: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  tags: [fast]
  before_script:
    - mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
  script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - cmake -S . -B build/mc -G "Ninja Multi-Config" -DCPACK_RPM_BUILD_SOURCE_DIRS_PREFIX=/storm
    - cd build/mc
    - cmake --build . --parallel --config Debug
    - cmake --build . --parallel --config Release
    - cmake --build . --parallel --config Coverage
    - cpack -C "Debug;Release" -G RPM
  artifacts:
    paths:
    - build/mc/storm-tape-*.rpm
    - build/mc/**/* 
  cache:
    - key: $CI_JOB_NAME
      paths:
        - $VCPKG_DEFAULT_BINARY_CACHE
  rules:
    - changes:
      - src/**/*
      - tests/**/*
      - CMakeLists.txt
      - version.txt
      - vcpkg.json
      - vcpkg-configuration.json
      - .gitlab-ci.yml
    - if: $CI_COMMIT_REF_NAME =~ /^\d+.\d+.\d+$/

test-storm-tape:debug:
  stage: test
  image: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  needs:
    - build-storm-tape
  script:
    - build/mc/tests/Debug/all.t
  rules:
    - changes:
      - src/**/*
      - tests/**/*
      - CMakeLists.txt
      - version.txt
      - vcpkg.json
      - vcpkg-configuration.json
      - .gitlab-ci.yml
    - if: $CI_COMMIT_REF_NAME =~ /^\d+.\d+.\d+$/

test-storm-tape:release:
  stage: test
  image: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  needs:
    - build-storm-tape
  script:
    - build/mc/tests/Release/all.t
  rules:
    - changes:
      - src/**/*
      - tests/**/*
      - CMakeLists.txt
      - version.txt
      - vcpkg.json
      - vcpkg-configuration.json
      - .gitlab-ci.yml
    - if: $CI_COMMIT_REF_NAME =~ /^\d+.\d+.\d+$/

test-storm-tape:coverage:
  stage: test
  image: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  needs:
    - build-storm-tape
  script:
    - build/mc/tests/Coverage/all.t
    - scripts/cov-report.sh
  artifacts:
    paths:
      - build/report
  rules:
    - changes:
      - src/**/*
      - tests/**/*
      - scripts/cov-report.sh
      - CMakeLists.txt
      - version.txt
      - vcpkg.json
      - vcpkg-configuration.json
      - .gitlab-ci.yml
    - if: $CI_COMMIT_REF_NAME =~ /^\d+.\d+.\d+$/

pages:
  stage: deploy
  needs:
    - test-storm-tape:coverage
  script:
    - cp -r build/report/ public/
    - ls -lah public/
  artifacts:
    paths:
      - public
  rules:
    - changes:
      - src/**/*
      - tests/**/*
      - scripts/cov-report.sh
      - CMakeLists.txt
      - version.txt
      - vcpkg.json
      - vcpkg-configuration.json
      - .gitlab-ci.yml
    - if: $CI_COMMIT_REF_NAME =~ /^\d+.\d+.\d+$/

build-docker:
  stage: deploy
  image: docker:latest
  tags: [fast]
  services:
    - docker:dind
  needs:
    - build-storm-tape
    - test-storm-tape:debug
    - test-storm-tape:release
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - mv build/mc/storm-tape-*.rpm ./docker
    - docker build docker --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  rules:
    - changes:
      - src/**/*
      - tests/**/*
      - docker/**/*
      - CMakeLists.txt
      - version.txt
      - vcpkg.json
      - vcpkg-configuration.json
      - .gitlab-ci.yml
    - if: $CI_COMMIT_REF_NAME =~ /^\d+.\d+.\d+$/

publish-rpms:
  stage: deploy
  image: $CI_REGISTRY_IMAGE/ci:$CI_COMMIT_REF_SLUG
  needs:
    - build-storm-tape
    - job: test-storm-tape:debug
      artifacts: false
    - job: test-storm-tape:release
      artifacts: false
  before_script:
    - VERSION="$(cat version.txt)"
    - PACKAGE_NAME=storm-tape
    - REPOSITORY="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic"

  script: |
    for rpm in build/mc/storm-tape-*.rpm; do
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${rpm}" \
        "${REPOSITORY}/${PACKAGE_NAME}/${VERSION}/${rpm}"
    done
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^\d+.\d+.\d+$/

# Avoid duplicate pipelines when a branch and an open merge request pointing to
# the same branch are both open at the same time
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
